# Generated by Django 3.0.10 on 2020-10-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20201030_0658'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sport',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
