# Generated by Django 3.0.10 on 2020-10-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2019)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('program', models.CharField(max_length=100, null=True)),
                ('card_set', models.CharField(max_length=100, null=True)),
                ('number', models.IntegerField(null=True)),
                ('team', models.CharField(max_length=100, null=True)),
                ('sequence', models.IntegerField(null=True)),
                ('tracked', models.BooleanField(default=False)),
                ('search_url', models.CharField(max_length=100, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Sport')),
            ],
        ),
    ]
