# Generated by Django 3.0.10 on 2020-10-29 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='search_url',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CardSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.URLField(max_length=100, null=True)),
                ('purchase_type', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('bids', models.IntegerField(null=True)),
                ('shipping_cost', models.IntegerField(null=True)),
                ('image', models.URLField(max_length=100, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
            ],
        ),
    ]
