# Generated by Django 3.0.10 on 2020-10-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20201029_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='sport',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
